export const countries = [
  { code: "US", name: "United States", phoneCode: "+1" },
  { code: "CA", name: "Canada", phoneCode: "+1" },
  { code: "BS", name: "Bahamas", phoneCode: "+1" },
  { code: "BB", name: "Barbados", phoneCode: "+1" },
  { code: "BM", name: "Bermuda", phoneCode: "+1" },
  { code: "DM", name: "Dominica", phoneCode: "+1" },
  { code: "DO", name: "Dominican Republic", phoneCode: "+1" },
  { code: "JM", name: "Jamaica", phoneCode: "+1" },
  { code: "TT", name: "Trinidad and Tobago", phoneCode: "+1" },
  { code: "EG", name: "Egypt", phoneCode: "+20" },
  { code: "MA", name: "Morocco", phoneCode: "+212" },
  { code: "DZ", name: "Algeria", phoneCode: "+213" },
  { code: "TN", name: "Tunisia", phoneCode: "+216" },
  { code: "LY", name: "Libya", phoneCode: "+218" },
  { code: "GM", name: "Gambia", phoneCode: "+220" },
  { code: "SN", name: "Senegal", phoneCode: "+221" },
  { code: "MR", name: "Mauritania", phoneCode: "+222" },
  { code: "ML", name: "Mali", phoneCode: "+223" },
  { code: "GN", name: "Guinea", phoneCode: "+224" },
  { code: "CI", name: "Ivory Coast", phoneCode: "+225" },
  { code: "BF", name: "Burkina Faso", phoneCode: "+226" },
  { code: "NE", name: "Niger", phoneCode: "+227" },
  { code: "TG", name: "Togo", phoneCode: "+228" },
  { code: "BJ", name: "Benin", phoneCode: "+229" },
  { code: "MU", name: "Mauritius", phoneCode: "+230" },
  { code: "LR", name: "Liberia", phoneCode: "+231" },
  { code: "SL", name: "Sierra Leone", phoneCode: "+232" },
  { code: "GH", name: "Ghana", phoneCode: "+233" },
  { code: "NG", name: "Nigeria", phoneCode: "+234" },
  { code: "TD", name: "Chad", phoneCode: "+235" },
  { code: "CF", name: "Central African Republic", phoneCode: "+236" },
  { code: "CM", name: "Cameroon", phoneCode: "+237" },
  { code: "CV", name: "Cape Verde", phoneCode: "+238" },
  { code: "ST", name: "Sao Tome and Principe", phoneCode: "+239" },
  { code: "GQ", name: "Equatorial Guinea", phoneCode: "+240" },
  { code: "GA", name: "Gabon", phoneCode: "+241" },
  { code: "CG", name: "Republic of the Congo", phoneCode: "+242" },
  { code: "CD", name: "Democratic Republic of the Congo", phoneCode: "+243" },
  { code: "AO", name: "Angola", phoneCode: "+244" },
  { code: "GW", name: "Guinea-Bissau", phoneCode: "+245" },
  { code: "SC", name: "Seychelles", phoneCode: "+248" },
  { code: "SD", name: "Sudan", phoneCode: "+249" },
  { code: "RW", name: "Rwanda", phoneCode: "+250" },
  { code: "ET", name: "Ethiopia", phoneCode: "+251" },
  { code: "SO", name: "Somalia", phoneCode: "+252" },
  { code: "DJ", name: "Djibouti", phoneCode: "+253" },
  { code: "KE", name: "Kenya", phoneCode: "+254" },
  { code: "TZ", name: "Tanzania", phoneCode: "+255" },
  { code: "UG", name: "Uganda", phoneCode: "+256" },
  { code: "BI", name: "Burundi", phoneCode: "+257" },
  { code: "MZ", name: "Mozambique", phoneCode: "+258" },
  { code: "ZM", name: "Zambia", phoneCode: "+260" },
  { code: "MG", name: "Madagascar", phoneCode: "+261" },
  { code: "RE", name: "Reunion", phoneCode: "+262" },
  { code: "ZW", name: "Zimbabwe", phoneCode: "+263" },
  { code: "NA", name: "Namibia", phoneCode: "+264" },
  { code: "MW", name: "Malawi", phoneCode: "+265" },
  { code: "LS", name: "Lesotho", phoneCode: "+266" },
  { code: "BW", name: "Botswana", phoneCode: "+267" },
  { code: "SZ", name: "Eswatini", phoneCode: "+268" },
  { code: "KM", name: "Comoros", phoneCode: "+269" },
  { code: "ZA", name: "South Africa", phoneCode: "+27" },
  { code: "ER", name: "Eritrea", phoneCode: "+291" },
  { code: "AW", name: "Aruba", phoneCode: "+297" },
  { code: "FO", name: "Faroe Islands", phoneCode: "+298" },
  { code: "GL", name: "Greenland", phoneCode: "+299" },
  { code: "GR", name: "Greece", phoneCode: "+30" },
  { code: "NL", name: "Netherlands", phoneCode: "+31" },
  { code: "BE", name: "Belgium", phoneCode: "+32" },
  { code: "FR", name: "France", phoneCode: "+33" },
  { code: "ES", name: "Spain", phoneCode: "+34" },
  { code: "GI", name: "Gibraltar", phoneCode: "+350" },
  { code: "PT", name: "Portugal", phoneCode: "+351" },
  { code: "LU", name: "Luxembourg", phoneCode: "+352" },
  { code: "IE", name: "Ireland", phoneCode: "+353" },
  { code: "IS", name: "Iceland", phoneCode: "+354" },
  { code: "AL", name: "Albania", phoneCode: "+355" },
  { code: "MT", name: "Malta", phoneCode: "+356" },
  { code: "CY", name: "Cyprus", phoneCode: "+357" },
  { code: "FI", name: "Finland", phoneCode: "+358" },
  { code: "BG", name: "Bulgaria", phoneCode: "+359" },
  { code: "HU", name: "Hungary", phoneCode: "+36" },
  { code: "LT", name: "Lithuania", phoneCode: "+370" },
  { code: "LV", name: "Latvia", phoneCode: "+371" },
  { code: "EE", name: "Estonia", phoneCode: "+372" },
  { code: "MD", name: "Moldova", phoneCode: "+373" },
  { code: "AM", name: "Armenia", phoneCode: "+374" },
  { code: "BY", name: "Belarus", phoneCode: "+375" },
  { code: "AD", name: "Andorra", phoneCode: "+376" },
  { code: "MC", name: "Monaco", phoneCode: "+377" },
  { code: "SM", name: "San Marino", phoneCode: "+378" },
  { code: "VA", name: "Vatican City", phoneCode: "+379" },
  { code: "UA", name: "Ukraine", phoneCode: "+380" },
  { code: "RS", name: "Serbia", phoneCode: "+381" },
  { code: "ME", name: "Montenegro", phoneCode: "+382" },
  { code: "HR", name: "Croatia", phoneCode: "+385" },
  { code: "SI", name: "Slovenia", phoneCode: "+386" },
  { code: "BA", name: "Bosnia and Herzegovina", phoneCode: "+387" },
  { code: "MK", name: "North Macedonia", phoneCode: "+389" },
  { code: "IT", name: "Italy", phoneCode: "+39" },
  { code: "RO", name: "Romania", phoneCode: "+40" },
  { code: "CH", name: "Switzerland", phoneCode: "+41" },
  { code: "CZ", name: "Czech Republic", phoneCode: "+420" },
  { code: "SK", name: "Slovakia", phoneCode: "+421" },
  { code: "LI", name: "Liechtenstein", phoneCode: "+423" },
  { code: "AT", name: "Austria", phoneCode: "+43" },
  { code: "GB", name: "United Kingdom", phoneCode: "+44" },
  { code: "DK", name: "Denmark", phoneCode: "+45" },
  { code: "SE", name: "Sweden", phoneCode: "+46" },
  { code: "NO", name: "Norway", phoneCode: "+47" },
  { code: "PL", name: "Poland", phoneCode: "+48" },
  { code: "DE", name: "Germany", phoneCode: "+49" },
  { code: "PE", name: "Peru", phoneCode: "+51" },
  { code: "MX", name: "Mexico", phoneCode: "+52" },
  { code: "CU", name: "Cuba", phoneCode: "+53" },
  { code: "AR", name: "Argentina", phoneCode: "+54" },
  { code: "BR", name: "Brazil", phoneCode: "+55" },
  { code: "CL", name: "Chile", phoneCode: "+56" },
  { code: "CO", name: "Colombia", phoneCode: "+57" },
  { code: "VE", name: "Venezuela", phoneCode: "+58" },
  { code: "GF", name: "French Guiana", phoneCode: "+594" },
  { code: "BO", name: "Bolivia", phoneCode: "+591" },
  { code: "GY", name: "Guyana", phoneCode: "+592" },
  { code: "EC", name: "Ecuador", phoneCode: "+593" },
  { code: "PY", name: "Paraguay", phoneCode: "+595" },
  { code: "MQ", name: "Martinique", phoneCode: "+596" },
  { code: "SR", name: "Suriname", phoneCode: "+597" },
  { code: "UY", name: "Uruguay", phoneCode: "+598" },
  { code: "MY", name: "Malaysia", phoneCode: "+60" },
  { code: "AU", name: "Australia", phoneCode: "+61" },
  { code: "ID", name: "Indonesia", phoneCode: "+62" },
  { code: "PH", name: "Philippines", phoneCode: "+63" },
  { code: "NZ", name: "New Zealand", phoneCode: "+64" },
  { code: "SG", name: "Singapore", phoneCode: "+65" },
  { code: "TH", name: "Thailand", phoneCode: "+66" },
  { code: "TL", name: "Timor-Leste", phoneCode: "+670" },
  { code: "AQ", name: "Antarctica", phoneCode: "+672" },
  { code: "BN", name: "Brunei", phoneCode: "+673" },
  { code: "NR", name: "Nauru", phoneCode: "+674" },
  { code: "PG", name: "Papua New Guinea", phoneCode: "+675" },
  { code: "TO", name: "Tonga", phoneCode: "+676" },
  { code: "SB", name: "Solomon Islands", phoneCode: "+677" },
  { code: "VU", name: "Vanuatu", phoneCode: "+678" },
  { code: "FJ", name: "Fiji", phoneCode: "+679" },
  { code: "PW", name: "Palau", phoneCode: "+680" },
  { code: "WF", name: "Wallis and Futuna", phoneCode: "+681" },
  { code: "CK", name: "Cook Islands", phoneCode: "+682" },
  { code: "NU", name: "Niue", phoneCode: "+683" },
  { code: "WS", name: "Samoa", phoneCode: "+685" },
  { code: "KI", name: "Kiribati", phoneCode: "+686" },
  { code: "NC", name: "New Caledonia", phoneCode: "+687" },
  { code: "TV", name: "Tuvalu", phoneCode: "+688" },
  { code: "PF", name: "French Polynesia", phoneCode: "+689" },
  { code: "TK", name: "Tokelau", phoneCode: "+690" },
  { code: "FM", name: "Micronesia", phoneCode: "+691" },
  { code: "MH", name: "Marshall Islands", phoneCode: "+692" },
  { code: "KZ", name: "Kazakhstan", phoneCode: "+7" },
  { code: "RU", name: "Russia", phoneCode: "+7" },
  { code: "JP", name: "Japan", phoneCode: "+81" },
  { code: "KR", name: "South Korea", phoneCode: "+82" },
  { code: "VN", name: "Vietnam", phoneCode: "+84" },
  { code: "KP", name: "North Korea", phoneCode: "+850" },
  { code: "HK", name: "Hong Kong", phoneCode: "+852" },
  { code: "MO", name: "Macau", phoneCode: "+853" },
  { code: "KH", name: "Cambodia", phoneCode: "+855" },
  { code: "LA", name: "Laos", phoneCode: "+856" },
  { code: "CN", name: "China", phoneCode: "+86" },
  { code: "BD", name: "Bangladesh", phoneCode: "+880" },
  { code: "TW", name: "Taiwan", phoneCode: "+886" },
  { code: "TR", name: "Turkey", phoneCode: "+90" },
  { code: "IN", name: "India", phoneCode: "+91" },
  { code: "PK", name: "Pakistan", phoneCode: "+92" },
  { code: "AF", name: "Afghanistan", phoneCode: "+93" },
  { code: "LK", name: "Sri Lanka", phoneCode: "+94" },
  { code: "MM", name: "Myanmar", phoneCode: "+95" },
  { code: "MV", name: "Maldives", phoneCode: "+960" },
  { code: "LB", name: "Lebanon", phoneCode: "+961" },
  { code: "JO", name: "Jordan", phoneCode: "+962" },
  { code: "SY", name: "Syria", phoneCode: "+963" },
  { code: "IQ", name: "Iraq", phoneCode: "+964" },
  { code: "KW", name: "Kuwait", phoneCode: "+965" },
  { code: "SA", name: "Saudi Arabia", phoneCode: "+966" },
  { code: "YE", name: "Yemen", phoneCode: "+967" },
  { code: "OM", name: "Oman", phoneCode: "+968" },
  { code: "PS", name: "Palestine", phoneCode: "+970" },
  { code: "AE", name: "United Arab Emirates", phoneCode: "+971" },
  { code: "IL", name: "Israel", phoneCode: "+972" },
  { code: "BH", name: "Bahrain", phoneCode: "+973" },
  { code: "QA", name: "Qatar", phoneCode: "+974" },
  { code: "BT", name: "Bhutan", phoneCode: "+975" },
  { code: "MN", name: "Mongolia", phoneCode: "+976" },
  { code: "NP", name: "Nepal", phoneCode: "+977" },
  { code: "IR", name: "Iran", phoneCode: "+98" },
  { code: "TJ", name: "Tajikistan", phoneCode: "+992" },
  { code: "TM", name: "Turkmenistan", phoneCode: "+993" },
  { code: "AZ", name: "Azerbaijan", phoneCode: "+994" },
  { code: "GE", name: "Georgia", phoneCode: "+995" },
  { code: "KG", name: "Kyrgyzstan", phoneCode: "+996" },
  { code: "UZ", name: "Uzbekistan", phoneCode: "+998" },
  { code: "SS", name: "South Sudan", phoneCode: "+211" },
];

export const getCountryOptions = (t) => {
  return countries.map((country) => ({
    value: country.code,
    label: t ? t(`${country.code.toLowerCase()}`, country.name) : country.name,
  }));
};

export const getCountryNameByCode = (countryCode) => {
  if (!countryCode) return "";

  const country = countries.find((c) => c.code === countryCode.toUpperCase());
  return country ? country.name : countryCode;
};

export const getPhoneCodeByCountry = (countryCode) => {
  if (!countryCode) return "";

  const country = countries.find((c) => c.code === countryCode.toUpperCase());
  return country ? country.phoneCode : "";
};

export const getCountryCodeByPhoneCode = (phoneCode) => {
  if (!phoneCode) return "";

  const formattedPhoneCode = phoneCode.startsWith("+")
    ? phoneCode
    : `+${phoneCode}`;

  const country = countries.find((c) => c.phoneCode === formattedPhoneCode);
  return country ? country.code : "";
};

export default countries;
